apiVersion: v1
kind: Namespace
metadata:
  name: mocklet
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mocklet
  namespace: mocklet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mocklet
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mocklet
  namespace: mocklet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mocklet
subjects:
  - kind: ServiceAccount
    name: mocklet
    namespace: mocklet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocklet
  labels:
    app: mocklet
  namespace: mocklet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocklet
  template:
    metadata:
      labels:
        app: mocklet
    spec:
      serviceAccountName: mocklet
      containers:
        - name: mocklet
          image: vineeth97/mocklet
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DEFAULT_NODE_NAME
              value: "mocklet"
            - name: NODE_CPU
              value: "200"
            - name: NODE_MEMORY
              value: "500Gi"
            - name: NUMBER_OF_PODS
              value: "10000"